from rest_framework.response import Response
from rest_framework.views import APIView

class Stories(APIView):
    def get(self, request):
        story_1 = {"title_en": "The Lost Cat", "title_uz": "Yo`qolgan Mushuk", "story_en": ["Emma was a little girl who loved her cat, Whiskers. One day, Whiskers went outside and did not come back. Emma looked everywhere, but she could not find him.", "She asked her neighbors, 'Have you seen my cat?' But no one had seen Whiskers.", "Emma was very sad. She made posters and put them around the neighborhood. The poster said, 'Lost Cat! His name is Whiskers. Please call if you see him.'", "The next morning, Emma heard a soft 'Meow' outside. She ran to the door and saw Whiskers sitting there, hungry and tired.", "'Oh, Whiskers! You are back!' she said happily and hugged him."], "story_uz": ["Emma ismli kichkina qizcha bor edi. U o`zining Whiskers ismli mushugini juda yaxshi ko`rardi. Bir kuni Whiskers tashqariga chiqdi va qaytib kelmadi. Emma uni hamma joydan qidirdi, lekin topa olmadi.", "U qo`shnilaridan so`radi: 'Mening mushugimni ko`rdingizmi?' Lekin hech kim Whiskersni ko`rmagan edi.", "Emma juda xafa bo`ldi. U e’lon tayyorladi va mahallaning turli joylariga osib chiqdi. E`londa shunday yozilgan edi: 'Yo`qolgan mushuk! Uning ismi Whiskers. Agar uni ko`rsangiz, iltimos, qo`ng`iroq qiling.'", "Ertasi kuni ertalab Emma tashqaridan yumshoq 'Meow' ovozini eshitdi. U eshikka chopdi va u yerda och va charchagan Whiskersni ko`rdi.", '"Oh, Whiskers! Sen qaytding!" - dedi Emma xursand bo`lib va uni quchoqlab oldi.', 'O`sha kundan boshlab, Emma har doim kechasi Whiskersni uyda saqladi. U uni yana yo`qotishni istamas edi.'], "images": [""]}
        story_2 = {"title_en": "The Lost Cat", "title_uz": "Yo`qolgan Mushuk", "story_en": ["Emma was a little girl who loved her cat, Whiskers. One day, Whiskers went outside and did not come back. Emma looked everywhere, but she could not find him.", "She asked her neighbors, 'Have you seen my cat?' But no one had seen Whiskers.", "Emma was very sad. She made posters and put them around the neighborhood. The poster said, 'Lost Cat! His name is Whiskers. Please call if you see him.'", "The next morning, Emma heard a soft 'Meow' outside. She ran to the door and saw Whiskers sitting there, hungry and tired.", "'Oh, Whiskers! You are back!' she said happily and hugged him."], "story_uz": ["Emma ismli kichkina qizcha bor edi. U o`zining Whiskers ismli mushugini juda yaxshi ko`rardi. Bir kuni Whiskers tashqariga chiqdi va qaytib kelmadi. Emma uni hamma joydan qidirdi, lekin topa olmadi.", "U qo`shnilaridan so`radi: 'Mening mushugimni ko`rdingizmi?' Lekin hech kim Whiskersni ko`rmagan edi.", "Emma juda xafa bo`ldi. U e’lon tayyorladi va mahallaning turli joylariga osib chiqdi. E`londa shunday yozilgan edi: 'Yo`qolgan mushuk! Uning ismi Whiskers. Agar uni ko`rsangiz, iltimos, qo`ng`iroq qiling.'", "Ertasi kuni ertalab Emma tashqaridan yumshoq 'Meow' ovozini eshitdi. U eshikka chopdi va u yerda och va charchagan Whiskersni ko`rdi.", '"Oh, Whiskers! Sen qaytding!" - dedi Emma xursand bo`lib va uni quchoqlab oldi.', 'O`sha kundan boshlab, Emma har doim kechasi Whiskersni uyda saqladi. U uni yana yo`qotishni istamas edi.'], "images": [""]}

        data = [
            story_1, 
            story_2,
        ]
        return Response(data)