# Generated by Django 4.2.6 on 2023-10-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_phones_test_phones_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
