# Generated by Django 4.2.6 on 2023-10-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
