# Generated by Django 4.2.6 on 2023-11-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_cards_phone_alter_phones_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
