# Generated by Django 4.2.6 on 2023-11-03 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_searchusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.searchusers'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.searchusers'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.searchusers'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.searchusers'),
        ),
    ]
