# Generated by Django 4.2.6 on 2023-11-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_users_userid_alter_cards_userid_alter_friends_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userId',
        ),
        migrations.AlterField(
            model_name='cards',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.DeleteModel(
            name='SearchUsers',
        ),
    ]
