# Generated by Django 4.2.6 on 2023-11-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_users_image_alter_friends_friendid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friendId',
        ),
        migrations.RemoveField(
            model_name='users',
            name='image',
        ),
    ]
