# Generated by Django 4.2.6 on 2023-11-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_friends_friendid_remove_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='index',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
