# Generated by Django 4.2.6 on 2023-11-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_friends_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
