# Generated by Django 4.2.6 on 2023-11-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
