# Generated by Django 4.2.7 on 2023-11-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='phones',
            name='userId',
        ),
        migrations.DeleteModel(
            name='Workers',
        ),
        migrations.RemoveField(
            model_name='users',
            name='about',
        ),
        migrations.RemoveField(
            model_name='users',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='users',
            name='fatherName',
        ),
        migrations.RemoveField(
            model_name='users',
            name='idNumber',
        ),
        migrations.RemoveField(
            model_name='users',
            name='isCar',
        ),
        migrations.RemoveField(
            model_name='users',
            name='isCourt',
        ),
        migrations.RemoveField(
            model_name='users',
            name='passportNumber',
        ),
        migrations.RemoveField(
            model_name='users',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='Phones',
        ),
    ]
