# Generated by Django 4.2.7 on 2023-11-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_name_users_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='surname',
            new_name='name',
        ),
    ]
